server:
  port: ${PORT:5000}



spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:ibadetetmek}


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 832987268023-boof49lop0bdvt03ai2t6rkl7k6l9fbk
            client-secret: 7pntQK6jkSS1Yd2qRwA9lC_r
          facebook:
            client-id: 577763016271805
            client-secret: 13832f619c67870dd3832e79d667ed86